### ISSUE TITLE
Add dummy django app for testing

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/django-admin-508#10]
The app is not testable on its own, its more of a library/theme package. To test it, it needs another app that uses it as a dependency to test it from.

**Comment by raftmsohani** [comment]
VENV::
1) clone package
	`git clone https://github.com/raft-tech/django-admin-508.git`
2) create a project directory for testing the package locally and change current directory:
	E.g: 
a.	`mkdir django_project_for_test`
b.	`cd django_project_for_test`
3) Add virtual env:
	`virtualenv venv`
4) activate virtualenv:
	`source venv/bin/activate`
5) Install django
	`pip install django`
6) change directory to local django-admin-508:
	`cd ../django-admin-508`
7) install local package:
	`pip install .`
8) create django project:
	`django-admin startproject testproject`
9) run migrations:
	`python manage.py migrate`
10) create superuser to be able to login to admin page
	`python manage.py createsuperuser`
11) add the package in settings above admin:
	```
    'admin_interface', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
```
